export const CAR_BRAND_OPTIONS = [
  { value: "alfa", label: "Alfa Romeo" },
  { value: "audi", label: "Audi" },
  { value: "bmw", label: "BMW" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "dacia", label: "Dacia" },
  { value: "ford", label: "Ford" },
  { value: "gmc", label: "GMC" },
  { value: "honda", label: "Honda" },
  { value: "jaguar", label: "Jaguar" },
  { value: "landrover", label: "Land Rover" },
  { value: "lexus", label: "Lexus" },
  { value: "mazda", label: "Mazda" },
  { value: "mercedes-benz", label: "Mercedes Benz" },
  { value: "nissan", label: "Nissan" },
  { value: "opel", label: "Opel" },
  { value: "peugeot", label: "Peugeot" },
  { value: "porsche", label: "Porsche" },
  { value: "renault", label: "Renault" },
  { value: "seat", label: "Seat" },
  { value: "skoda", label: "Skoda" },
  { value: "toyota", label: "Toyota" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "volvo", label: "Volvo" },
];

export const CAR_MODEL_OPTIONS = [
  { key: "alfa", value: "Giulia", label: "Giulia" },
  { key: "alfa", value: "Mito", label: "Mito" },
  { key: "alfa", value: "Stelvio", label: "Stelvio" },
  { key: "--", value: "--", label: "----------------" },
  { key: "audi", value: "a3", label: "A3" },
  { key: "audi", value: "a4", label: "A4" },
  { key: "audi", value: "a5", label: "A5" },
  { key: "audi", value: "a6", label: "A6" },
  { key: "audi", value: "a7", label: "A7" },
  { key: "audi", value: "a8", label: "A8" },
  { key: "--", value: "--", label: "----------------" },
  { key: "bmw", value: "1 Series", label: "1 Series" },
  { key: "bmw", value: "2 Series", label: "2 Series" },
  { key: "bmw", value: "3 Series", label: "3 Series" },
  { key: "bmw", value: "4 Series", label: "4 Series" },
  { key: "bmw", value: "5 Series", label: "5 Series" },
  { key: "bmw", value: "6 Series", label: "6 Series" },
  { key: "bmw", value: "7 Series", label: "7 Series" },
  { key: "bmw", value: "8 Series", label: "8 Series" },
  { key: "--", value: "--", label: "----------------" },
  { key: "chevrolet", value: "cruze", label: "Cruze" },
  { key: "chevrolet", value: "corvette", label: "Corvette" },
  { key: "--", value: "--", label: "----------------" },
  { key: "dacia", value: "logan", label: "Logan" },
  { key: "dacia", value: "duster", label: "Duster" },
  { key: "--", value: "--", label: "----------------" },
  { key: "ford", value: "fiesta", label: "Fiesta" },
  { key: "ford", value: "focus", label: "Focus" },
  { key: "ford", value: "mondeo", label: "Mondeo" },
  { key: "--", value: "--", label: "----------------" },
  { key: "gmc", value: "sierra", label: "Sierra" },
  { key: "--", value: "--", label: "----------------" },
  { key: "honda", value: "accord", label: "Accord" },
  { key: "honda", value: "civic", label: "Civic" },
  { key: "honda", value: "crv", label: "CR-V" },
  { key: "--", value: "--", label: "----------------" },
  { key: "jaguar", value: "xe", label: "XE" },
  { key: "jaguar", value: "xf", label: "XF" },
  { key: "jaguar", value: "xj", label: "XJ" },
  { key: "--", value: "--", label: "----------------" },
  { key: "landrover", value: "freelander", label: "Freelander" },
  { key: "landrover", value: "rangerover", label: "Range Rover Sport" },
  { key: "landrover", value: "evoque", label: "Range Rover Evoque" },
  { key: "--", value: "--", label: "----------------" },
  { key: "lexus", value: "es300", label: "ES 300" },
  { key: "lexus", value: "rx350", label: "RX 350" },
  { key: "lexus", value: "gx460", label: "GX 460" },
  { key: "--", value: "--", label: "----------------" },
  { key: "mazda", value: "cx30", label: "CX-30" },
  { key: "mazda", value: "mazda3", label: "3" },
  { key: "mazda", value: "mazda6", label: "6" },
  { key: "--", value: "--", label: "----------------" },
  { key: "mercedes-benz", value: "c-class", label: "C-Class" },
  { key: "mercedes-benz", value: "e-class", label: "E-Class" },
  { key: "mercedes-benz", value: "s-class", label: "S-Class" },
  { key: "mercedes-benz", value: "gle-class", label: "GLC" },
  { key: "mercedes-benz", value: "gle-class", label: "GLE" },
  { key: "mercedes-benz", value: "glk-class", label: "GLS" },
  { key: "mercedes-benz", value: "g-class", label: "G-Class" },
  { key: "--", value: "--", label: "----------------" },
  { key: "nissan", value: "gtr", label: "GT-R" },
  { key: "nissan", value: "qashqai", label: "Qashqai" },
  { key: "--", value: "--", label: "----------------" },
  { key: "opel", value: "astra", label: "Astra" },
  { key: "opel", value: "corsa", label: "Corsa" },
  { key: "opel", value: "insignia", label: "Insignia" },
  { key: "--", value: "--", label: "----------------" },
  { key: "peugeot", value: "208", label: "208" },
  { key: "peugeot", value: "308", label: "308" },
  { key: "peugeot", value: "508", label: "508" },
  { key: "--", value: "--", label: "----------------" },
  { key: "porsche", value: "718", label: "718" },
  { key: "porsche", value: "911", label: "911" },
  { key: "porsche", value: "panamera", label: "Panamera" },
  { key: "porsche", value: "cayenne", label: "Cayenne" },
  { key: "--", value: "--", label: "----------------" },
  { key: "renault", value: "clio", label: "Clio" },
  { key: "renault", value: "megane", label: "Megane" },
  { key: "renault", value: "talisman", label: "Talisman" },
  { key: "--", value: "--", label: "----------------" },
  { key: "seat", value: "ibiza", label: "Ibiza" },
  { key: "seat", value: "leon", label: "Leon" },
  { key: "seat", value: "exeo", label: "Exeo" },
  { key: "--", value: "--", label: "----------------" },
  { key: "skoda", value: "fabia", label: "Fabia" },
  { key: "skoda", value: "octavia", label: "Octavia" },
  { key: "skoda", value: "superb", label: "Superb" },
  { key: "--", value: "--", label: "----------------" },
  { key: "toyota", value: "camry", label: "Camry" },
  { key: "toyota", value: "corolla", label: "Corolla" },
  { key: "toyota", value: "land-cruiser", label: "Land Cruiser" },
  { key: "--", value: "--", label: "----------------" },
  { key: "volkswagen", value: "arteon", label: "Arteon" },
  { key: "volkswagen", value: "golf", label: "Golf" },
  { key: "volkswagen", value: "passat", label: "Passat" },
  { key: "volkswagen", value: "polo", label: "Polo" },
  { key: "volkswagen", value: "tiguan", label: "Tiguan" },
  { key: "volkswagen", value: "Touareg", label: "Touareg" },
  { key: "--", value: "--", label: "----------------" },
  { key: "volvo", value: "s40", label: "S40" },
  { key: "volvo", value: "s60", label: "S60" },
  { key: "volvo", value: "s90", label: "S90" },
  { key: "volvo", value: "xc60", label: "XC60" },
  { key: "volvo", value: "xc90", label: "XC90" },
];

export const CAR_BODY_TYPE_OPTIONS = [
  { value: "sedan", label: "Sedan" },
  { value: "wagon", label: "Wagon" },
  { value: "suv", label: "SUV" },
  { value: "hatchback", label: "Hatchback" },
  { value: "coupe", label: "Coupe" },
  { value: "convertible", label: "Convertible" },
  { value: "van", label: "Van/Minivan" },
  { value: "other", label: "Other" },
];

export const CAR_SECOND_CONDITION_OPTIONS = [
  { value: "afterCrash", label: "After Crash" },
  { value: "engineIssue", label: "Engine Issue" },
  { value: "gearIssue", label: "Gearbox Issue" },
  { value: "needBodyRepair", label: "Needs Body Repair" },
  { value: "needRepair", label: "Needs Repair" },
  { value: "needRepainting", label: "Needs Repainting" },
  { value: "electricalIssue", label: "Electrical Issue" },
  { value: "suspensionIssue", label: "Suspension Issue" },
  { value: "brakeIssue", label: "Brake Issue" },
  { value: "interiorDamage", label: "Interior Damage" },
  { value: "noFault", label: "No Fault" },
];

export const CAR_KEY_FEATURES_OPTIONS = [
  // Audio and Technology
  {
    value: "audio&tech",
    label:
      "--------------------------  Audio & Technology  --------------------------",
  },
  { value: "navigation", label: "Navigation System" },
  { value: "bluetooth", label: "Bluetooth Connectivity" },
  { value: "appleCarplay", label: "Apple CarPlay" },
  { value: "androidAuto", label: "Android Auto" },
  { value: "premiumSound", label: "Premium Sound System" },
  // Comfort and Optional Equipment
  {
    value: "comfort",
    label:
      "--------------------------  Comfort & Optionals  -------------------------",
  },
  { value: "leatherSeats", label: "Leather Seats" },
  { value: "heatedSeats", label: "Heated Seats" },
  { value: "ventilatedSeats", label: "Ventilated Seats" },
  { value: "electricSeats", label: "Electric Seats" },
  { value: "sportSeats", label: "Sport Seats" },
  { value: "sunroof", label: "Sunroof/Moonroof" },
  { value: "keylessEntry", label: "Keyless Entry" },
  { value: "keylessGo", label: "Keyless Go" },
  { value: "remoteStart", label: "Remote Start" },
  { value: "airConditioning", label: "Air Conditioning" },
  { value: "climateControl", label: "Climate Control" },
  { value: "armrest", label: "Armrest" },
  { value: "leathersteering", label: "Leather Steering Wheel" },
  {
    value: "electricsteering",
    label: "Electrically adjustable steering wheel",
  },
  { value: "steeringcontrols", label: "Steering Wheel Controls" },
  { value: "rainsensor", label: "Rain sensor" },
  { value: "elecwindows", label: "Electric front windows" },
  { value: "elecrearwindows", label: "Electric rear windows" },

  {
    value: "electric",
    label:
      "-----------------  Electronics & Assistance Systems  ----------------",
  },
  { value: "adaptiveCruiseControl", label: "Adaptive Cruise Control" },
  { value: "ledheadlights", label: "LED Headlights" },
  { value: "adaptiveHeadlights", label: "Adaptive Headlights" },
  { value: "daylights", label: "Daylights" },
  { value: "ledtaillights", label: "LED Taillights" },
  { value: "followme", label: "Follow me home" },
  { value: "parkingSens", label: "Front parking sensors" },
  { value: "parkingSensors", label: "Rear parking sensors" },
  { value: "automaticparking", label: "Automatic parking system" },
  { value: "rearviewCamera", label: "Rearview Camera" },
  { value: "360Camera", label: "360° Camera" },
  { value: "mirrors", label: "Electrically adjustable exterior mirrors" },
  { value: "heatedMirrors", label: "Heated exterior mirrors" },
  { value: "powerFolding", label: "Power-folding exterior mirrors" },
  { value: "laneAssist", label: "Lane Assist" },
  { value: "brakeAssist", label: "Brake Assist" },
  {
    value: "automaticEmergencyBraking",
    label: "Automatic Emergency Braking",
  },
  { value: "tractionControl", label: "Traction Control" },
  { value: "autoHold", label: "Auto Hold" },
  { value: "speedometerRecognition", label: "Speed sign recognition system" },
  { value: "highBeam", label: "High Beam Assistance" },
  { value: "startStop", label: "Start/Stop system" },
  { value: "electricparking", label: "Electric parking brake" },

  {
    value: "performance",
    label:
      "------------------------------  Performance  ------------------------------",
  },
  { value: "alloys", label: "Alloy Wheels" },
  { value: "suspension ", label: "Electronically controlled suspension" },
  { value: "airSuspension ", label: "Air suspension" },

  {
    value: "safety",
    label:
      "-----------------------------------  Safety  ----------------------------------",
  },
  { value: "abs", label: "ABS" },
  { value: "esp", label: "ESP" },
  { value: "assistedbraking", label: "Assisted braking" },
  { value: "automatic112", label: "Automatic 112 call" },
  { value: "dairbag", label: "Driver Airbag" },
  { value: "pairbag", label: "Passenger Airbag" },
  { value: "fairbag", label: "Front head Airbags" },
  { value: "lairbag", label: "Driver & Passenger side Airbag" },
  { value: "rairbag", label: "Rear head Airbags" },
  { value: "piciairbag", label: "Legs Airbag" },
  { value: "isofix", label: "Isofix" },
];

export const CAR_COLOR_OPTIONS = [
  {
    value: "white",
    label: "White",
  },
  {
    value: "gray",
    label: "Gray",
  },
  {
    value: "beige",
    label: "Beige",
  },
  {
    value: "cognac",
    label: "Cognac",
  },
  {
    value: "black",
    label: "Black",
  },
  {
    value: "red",
    label: "Red",
  },
  {
    value: "blue",
    label: "Blue",
  },
  {
    value: "green",
    label: "Green",
  },
  {
    value: "other",
    label: "Other",
  },
];

export const CAR_CONDITION_OPTIONS = [
  { value: "BRAND_NEW", label: "Brand New" },
  { value: "USED", label: "Used" },
];

export const CAR_FUELTYPE_OPTIONS = [
  { value: "PETROL", label: "Petrol" },
  { value: "DIESEL", label: "Diesel" },
  { value: "ELECTRIC", label: "Electric" },
  { value: "HYBRID", label: "Hybrid" },
];

export const CAR_TRANSMISSION_OPTIONS = [
  { value: "AUTOMATIC", label: "Automatic" },
  { value: "MANUAL", label: "Manual" },
];

export const CAR_DRIVETRAIN_OPTIONS = [
  { value: "FWD", label: "Front-Wheel Drive (FWD)" },
  { value: "RWD", label: "Rear-Wheel Drive (RWD)" },
  { value: "AWD", label: "All-Wheel Drive (AWD)" },
];

export const CAR_YEAR_OPTIONS = [
  { value: "2025", label: "2025" },
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003" },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
  { value: "1999", label: "1999" },
  { value: "1998", label: "1998" },
  { value: "1997", label: "1997" },
  { value: "1996", label: "1996" },
  { value: "1995", label: "1995" },
  { value: "1994", label: "1994" },
  { value: "1993", label: "1993" },
  { value: "1992", label: "1992" },
];

export const CAR_YEAR_RANGE_OPTIONS = [
  { value: "1990-1995", label: "1990 - 1995" },
  { value: "1995-2000", label: "1995-2000" },
  { value: "2000-2005", label: "2000 - 2005" },
  { value: "2005-2010", label: "2005 - 2010" },
  { value: "2010-2015", label: "2010 - 2015" },
  { value: "2015-2020", label: "2015 - 2025" },
  { value: "2020-2025", label: "2020 - 2025" },
];

export const CAR_PRICE_RANGE_OPTIONS = [
  { value: "0-5000", label: "Under 5k" },
  { value: "5000-10000", label: "5 - 10k" },
  { value: "10000-30000", label: "10 - 30k" },
  { value: "30000-50000", label: "30 - 50k" },
  { value: "50000-100000", label: "50 - 100k" },
  { value: "100000-200000", label: "Over 100k" },
  { value: "custom", label: "Custom" },
];
